### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by ChaeByunghoon** [hea9549/msa-ddd-eventsourcing#3]
@OnEvent 로 어노테이션이 걸리는 함수의 네이밍을 규칙을 정하면 좋을것 같습니다!

**Comment by hihiboss** [comment]
보니까 대부분 on[Aggregate][Action]Event 형식으로 하셔서 그냥 이대로 가면 좋을것 같습니다~

**Comment by ChaeByunghoon** [comment]
넵!
